# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /catalog-service

# Spring Configurations
spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog-db
      database: catalog-db
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-update
        jdbc:
          lob:
            non_contextual_creation: false
  h2:
    console:
      enabled: true
      path: /h2-console